server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: API-Gateway
  cloud:
    config:
      enabled: false

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
